# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aca66a8632b4fd840585449e359dc4f47c863495af7cef88b511a924e55aebe348c69e9e6c7ede7d46014a27c467d2f3e0663d74fedb2a563ea1a024c721c4f2

test:
  secret_key_base: 3c859459566517dc3aa9ca9819136d49847b4cb273ec89b439fd0f80e9d11f3e0e5d65e186748f72cdc4f3bc4059d966c88ac429b9b9f1d54aba02f7afd73b7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
